backend/models/Files.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "files".
 *
 * @property int $id
 * @property string $title
 * @property string $description
 * @property string $size
 * @property string $created_at
 * @property int $file_categories_id
 * @property int $upload_by_users_id
 * @property string $filename
 *
 * @property Comments[] $comments
 * @property FileCategories $fileCategories
 * @property Users $uploadByUsers
 * @property Ratings[] $ratings
 * @property UserDownloads[] $userDownloads
 */
class Files extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'files';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'file_categories_id', 'upload_by_users_id'], 'required'],
            [['description'], 'string'],
            [['created_at'], 'safe'],
            [['file_categories_id', 'upload_by_users_id'], 'integer'],
            [['title', 'size'], 'string', 'max' => 100],
            [['filename'], 'string', 'max' => 255],
            [['file_categories_id'], 'exist', 'skipOnError' => true, 'targetClass' => FileCategories::className(), 'targetAttribute' => ['file_categories_id' => 'id']],
            [['upload_by_users_id'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['upload_by_users_id' => 'id']],
        ];
    }


    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'description' => 'Description',
            'size' => 'Size',
            'created_at' => 'Created At',
            'file_categories_id' => 'File Categories ID',
            'upload_by_users_id' => 'Upload By Users ID',
            'filename' => 'File',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getComments()
    {
        return $this->hasMany(Comments::className(), ['files_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFileCategories()
    {
        return $this->hasOne(FileCategories::className(), ['id' => 'file_categories_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUploadByUsers()
    {
        return $this->hasOne(Users::className(), ['id' => 'upload_by_users_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRatings()
    {
        return $this->hasMany(Ratings::className(), ['files_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserDownloads()
    {
        return $this->hasMany(UserDownloads::className(), ['files_id' => 'id']);
    }
}

backend/controllers/FilesController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Files;
use backend\models\Users;
use backend\models\Comments;
use backend\models\Ratings;
use backend\models\FilesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\db\ActiveRecord;
use yii\db\ActiveQuery;
use backend\controllers\SessionController;
/**
 * FilesController implements the CRUD actions for Files model.
 */
class FilesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Files models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new FilesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Files model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        //$omg = Yii::$app->request->post();
        //$model3= Comments::find()->where(['files_id'=>$id])->all();
        $model2 = new Comments();
        if ($model2->load(Yii::$app->request->post())) {
            $model2->created_at = date('Y-m-d H:i:s');
            $model2->files_id=$_SESSION['files_id'];
            $model2->comment_by_users_id = $_SESSION['id'];
            $model2->save();
            return $this->redirect(['view', 'id' => $model2 ->files_id,]);
        }
        
        $model3 = new Ratings();
        if ($model3->load(Yii::$app->request->post())) {
            //$model3->created_at = date('Y-m-d H:i:s');
            $model3->files_id=$_SESSION['files_id'];
            $model3->rating_by_users_id = $_SESSION['id'];
            $model3->save();
            return $this->redirect(['view', 'id' => $model2 ->files_id,]);
        }
        
        return $this->render('view', [
            'model' => $this->findModel($id),
            'model3'=> $model3,
            'model2'=> $model2,
        ]);
    }
    

    /**
     * Creates a new Files model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Files();
        //$session = Yii::$app->session;

        if ($model->load(Yii::$app->request->post())) {
            $model->created_at=date('Y-m-d H:i:s');
            $model->save();
            
            $userId=$model->upload_by_users_id;
            $user = $this->findUser($userId);
            $user_name=$user->fullname;
            $judul=$model->title;
            $file = UploadedFile::getInstance($model,'filename');
            $siz=$file->getSize();
            if($siz > 1000){
                $siz = number_format($siz / 1000);
                $simpan = $siz.' Kb';
            }
            else if($siz > 1000000){
                $siz = number_format($siz / 1000);
                $simpan = $siz.' Mb';
            }
            $model->size=$simpan;
            $fileName='file_'.$judul.'_'.$user_name.'.'.$file->getExtension();
            $file->saveAs(Yii::getAlias('@filePath').'/'.$fileName);
            $model->filename=$fileName;
            $model->save();
            
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Files model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model->created_at=date('Y-m-d H:i:s');
            $model->save();
            
            $userId=$model->upload_by_users_id;
            $user = $this->findUser($userId);
            $user_name=$user->fullname;
            $judul=$model->title;
            $file = UploadedFile::getInstance($model,'filename');
            $fileName='file_'.$judul.'_'.$user_name.'.'.$file->getExtension();
            $file->saveAs(Yii::getAlias('@filePath').'/'.$fileName);
            $model->filename=$fileName;
            $model->save();
            
            //$model->size=$file->getSize();
            //$model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Files model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->deleteOther($id);
        $this->findModel($id)->delete();
        

        return $this->redirect(['index']);
    }

    /**
     * Finds the Files model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Files the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Files::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    protected function findUser($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    protected function deleteOther($id)
    {
        Comments::deleteAll('files_id = :id', [':id' => $id]);
        Ratings::deleteAll('files_id = :id', [':id' => $id]);
    }
    
}

frontend/controllers/FilesController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Files;
use frontend\models\Users;
use frontend\models\Comments;
use frontend\models\Ratings;
use frontend\models\UserDownloads;
use frontend\models\FilesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\db\ActiveRecord;
use yii\db\ActiveQuery;
use frontend\controllers\SessionController;
/**
 * FilesController implements the CRUD actions for Files model.
 */
class FilesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Files models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new FilesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            //'model' => Files::findModel($id)
        ]);
    }

    /**
     * Displays a single Files model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        //$omg = Yii::$app->request->post();
        //$model3= Comments::find()->where(['files_id'=>$id])->all();
        $model2 = new Comments();
        if ($model2->load(Yii::$app->request->post())) {
            $model2->created_at = date('Y-m-d H:i:s');
            $model2->files_id=$_SESSION['files_id'];
            $model2->comment_by_users_id = $_SESSION['id'];
            $model2->save();
            return $this->redirect(['view', 'id' => $model2 ->files_id,]);
        }
		
		$model3 = new Ratings();
		if ($model3->load(Yii::$app->request->post())) {
            //$model3->created_at = date('Y-m-d H:i:s');
            $model3->files_id=$_SESSION['files_id'];
            $model3->rating_by_users_id = $_SESSION['id'];
            $model3->save();
            return $this->redirect(['view', 'id' => $model3 ->files_id,]);
        }

      
            
            //$this->actionDownload();        
            
           // return $this->redirect(['view', 'id' => $model4 ->files_id,]);
        


    
        return $this->render('view', [
            'model' => $this->findModel($id),
            'model3'=> $model3,
            'model2'=> $model2,
            //'model4'=> $model4,
        ]);
    }
    
    public function actionDownload($id)
    {
        $model4 = new UserDownloads();
        $model4->created_at = date('Y-m-d H:i:s');
        $model4->files_id=$id;
        $model4->download_by_users_id = $_SESSION['id'];
        $model4->save();
        $data = Files::findOne($id);
        header('Content-Type:'.pathinfo(Yii::getAlias('@fileUrl').'/'.$data->filename, PATHINFO_EXTENSION));
        header('Content-Disposition: attachment; filename='.$data->filename);
        return readfile(Yii::getAlias('@fileUrl').'/'.$data->filename);
    }
    
    /**
     * Creates a new Files model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Files();
        //$session = Yii::$app->session;

        if ($model->load(Yii::$app->request->post())) {
            $model->created_at=date('Y-m-d H:i:s');
            $model->save();
            
            $userId=$model->upload_by_users_id;
            $user = $this->findUser($userId);
            $user_name=$user->fullname;
            $judul=$model->title;
            $file = UploadedFile::getInstance($model,'filename');
            $siz=$file->getSize();
            if($siz > 1000){
                $siz = number_format($siz / 1000);
                $simpan = $siz.' Kb';
            }
            else if($siz > 1000000){
                $siz = number_format($siz / 1000);
                $simpan = $siz.' Mb';
            }
            $model->size=$simpan;
            $fileName='file_'.$judul.'_'.$user_name.'.'.$file->getExtension();
            $file->saveAs(Yii::getAlias('@filePath').'/'.$fileName);
            $model->filename=$fileName;
            $model->save();
            
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Files model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
			$model->created_at=date('Y-m-d H:i:s');
			$model->save();
			
			$userId=$model->upload_by_users_id;
			$user = $this->findUser($userId);
			$user_name=$user->fullname;
			$judul=$model->title;
			$file = UploadedFile::getInstance($model,'filename');
			$fileName='file_'.$judul.'_'.$user_name.'.'.$file->getExtension();
			$file->saveAs(Yii::getAlias('@filePath').'/'.$fileName);
			$model->filename=$fileName;
			$model->save();
			
			//$model->size=$file->getSize();
			//$model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Files model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
		$this->deleteOther($id);
		$this->findModel($id)->delete();
		

        return $this->redirect(['users/view', 'id' => $_SESSION['id']]);
    }

    /**
     * Finds the Files model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Files the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Files::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
	
	protected function findUser($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
	
	protected function deleteOther($id)
    {
        Comments::deleteAll('files_id = :id', [':id' => $id]);
		Ratings::deleteAll('files_id = :id', [':id' => $id]);
    }
	
}

frontend/views/files/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use frontend\models\FileCategories;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model backend\models\Files */
/* @var $form yii\widgets\ActiveForm */

$categories=FileCategories::find()->all();

$listData=ArrayHelper::map($categories,'id','name');
?>

<div class="container">
<div class="files-form">
    <font face="Century Gothic" size="3">
    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>
	
	<?= $form->field($model, 'upload_by_users_id')->hiddenInput(['value'=>$_SESSION['id']])->label(false) ?>
	
	<?= $form->field($model, 'filename')->fileInput() ?>

    <?= $form->field($model, 'file_categories_id')->dropDownList(
		 $listData,
        ['id'=>'name']) ?>
	
	

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>
    </font>
    <?php ActiveForm::end(); ?>

</div>
</div>

frontend/views/files/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\FilesSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="files-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'size') ?>

    <?= $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'file_categories_id') ?>

    <?php // echo $form->field($model, 'upload_by_users_id') ?>

    <?php // echo $form->field($model, 'filename') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/files/coba.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\Comments */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="comments-form">
	<font face="Century Gothic" size="3">
    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model2, 'comment')->textArea() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/files/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\Files */

$this->title = 'Create Files';
//$this->params['breadcrumbs'][] = ['label' => 'Files', 'url' => ['index']];
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
<div class="files-create">

    <font face="Oswald" size="6"><?= Html::encode($this->title) ?></font>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>
</div>

frontend/views/files/index.php
<?php
    use yii\helpers\Html;
    use yii\db\Query;
    
    $this->title = 'MyRepo';
    $id = $_GET['id'];
?>
<header>
    <link rel="stylesheet" href="../assets/index.css" >
    <style type="text/css">
    
    </style>
</header>
<div class="row" style="padding:5% 0;">
            <div class="col-lg-3">
                <ul class="list-group">
                  <li class="list-group-item"><?= Html::a('Photos', ['files', 'id' => 1], ['style' => 'text-decoration:none']); ?></li>
                  <li class="list-group-item">Dapibus ac facilisis in</li>
                  <li class="list-group-item">Morbi leo risus</li>
                  <li class="list-group-item"><a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Porta ac consectetur ac</a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                  </ul>      

                  </li>
                  <li class="list-group-item">Vestibulum at eros</li>
                </ul>
            </div>
            <div class="col-lg-8">
                <div class="">
                    <ul class="event-list">
                        <?php                
                            $query = (new Query())
                                            ->from('files')
                                            ->where(['file_categories_id'=>$id]);
                            foreach($query->each() as $data){ ?>
                        <li>
                            <time datetime="2014-07-20" style="background-color: rgb(197, 44, 102);">

                                <span class="month" style="bottom:0">Music</span>
                                <span class="year">2014</span>
                                <span class="time">ALL DAY</span>
                            </time>
                            <img alt="Independence Day" src="https://farm4.staticflickr.com/3100/2693171833_3545fb852c_q.jpg" />
                            <div class="info" style="padding-left:2%;">
                                <?= Html::a($data['title'], ['files/view', 'id' => $data['id']], ['class'=>'title', 'style'=>'margin-top:5%;']); ?>
                                <p class="desc"><?= $data['filename']?></p>
                                <p class="desc">Uploaded at : <?= $data['created_at']?></p>
                            </div>
                            <div class="social">
                                <ul>
                                    <li class="facebook" style="width:33%;"><a href="#facebook"><span class="fa fa-facebook"></span></a></li>
                                    <li class="twitter" style="width:34%;"><a href="#twitter"><span class="fa fa-twitter"></span></a></li>
                                    <li class="google-plus" style="width:33%;"><a href="#google-plus"><span class="fa fa-google-plus"></span></a></li>
                                </ul>
                            </div>
                        </li>
                        <?php 
                            }
                        ?>
                    </ul>
                </div>
            </div>
        </div>

frontend/views/files/rating.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\Comments */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="rating-form">

    <?php $form = ActiveForm::begin(); ?>


    <?= $form->field($model3, 'value')->radioList(array(1=>'1',2=>'2',3=>'3',4=>'4',5=>'5')); ?>

    <?= $form->field($model3, 'rating_by_users_id')->hiddenInput(['value'=>$_SESSION['id']])->label(false) ?>

        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/files/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Files */

$this->title = 'Update Files: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Files', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="files-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>